platforms: Remove unused inventory pointers
Addresses the following related clang-tidy warning:

```
../src/platforms/everest.hpp:75:16: error: private field 'inventory' is not used [clang-diagnostic-unused-private-field,-warnings-as-errors]
    Inventory* inventory;
               ^
```

Signed-off-by: Andrew Jeffery <andrew@aj.id.au>